using System;
using System.Collections.Generic;

namespace Problem12
{
    /*
        The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

        1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

        Let us list the factors of the first seven triangle numbers:

         1: 1
         3: 1,3
         6: 1,2,3,6
        10: 1,2,5,10
        15: 1,3,5,15
        21: 1,3,7,21
        28: 1,2,4,7,14,28
        We can see that 28 is the first triangle number to have over five divisors.

        What is the value of the first triangle number to have over five hundred divisors?


        WARNING: TAKES LONG TO COMPUTE (up to 30 min on fairly decent cpu)
    */
    class Program
    {
        private static void GetTriangleNumbersByIndex(int number, List<long> list = null)
        {
            if (number < 1) return;
            if (list == null) list = new List<long>();
            if (number == 1) //Specialization
            {
                list.Add(1);
                return;
            }
            if(list.Count <= (number-2)) GetTriangleNumbersByIndex(number - 1, list);
            list.Add(list[number - 2] + number);
        }

        private static int GetDivisorCount(long num)
        {
            var count = 0;
            for (var iii = 1; iii <= num; ++iii)
                if ((num % iii) == 0) ++count;
            return count;
        }

        static void Main(string[] args)
        {            
            var list = new List<long>(); //triangle numbers
            var index = 0;
            var maxCandidate = 0;
            while(true)
            {
                GetTriangleNumbersByIndex(++index, list);
                var candidate = GetDivisorCount(list[index - 1]);
                if(candidate > maxCandidate)
                {
                    maxCandidate = candidate;
                    Console.WriteLine("New candidate: " + list[index - 1] + "; With: " + candidate + " divisors.");
                    if (candidate >= 500)
                    {
                        Console.WriteLine("Finished: " + list[index - 1]);
                        break;
                    }
                }
            }

            Console.ReadLine();
        }
    }
}
